import { useEffect, useState } from "react";

const api="http://127.0.0.1:3000/api";
const post=(path:string,body:Record<string,unknown>={})=>fetch(`${api}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}).then(response=>response.json());

export default function ButtonRuntime(){const [message,setMessage]=useState("");useEffect(()=>{const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>(".dash button"));const find=(text:string)=>buttons.find(button=>button.textContent?.includes(text));const pause=find("Pause");const speed=find("×");const run=find("New run");const blinds=find("Close blinds");const fan=find("Use fan");const nav=[find("Apartment"),find("Analytics"),find("Billing")].filter(Boolean) as HTMLButtonElement[];let currentSpeed=60;
const setNav=(active:HTMLButtonElement,target:string)=>{nav.forEach(button=>button.classList.toggle("active",button===active));document.querySelector(target)?.scrollIntoView({behavior:"smooth",block:"start"});};
const onApartment=()=>setNav(nav[0],".main-grid");const onAnalytics=()=>setNav(nav[1],".lower");const onBilling=()=>setNav(nav[2],".lower .card:last-child");
const onPause=async()=>{const state=await post("/simulation/pause",{paused:!pause?.textContent?.includes("Resume")});if(pause)pause.textContent=state.paused?"▶  Resume":"Ⅱ  Pause";};
const onSpeed=async()=>{const next=([1,10,60] as const)[([1,10,60] as const).indexOf(currentSpeed as 1|10|60)+1]??1;const state=await post("/simulation/speed",{speed:next});currentSpeed=state.speed;if(speed)speed.textContent=`${currentSpeed}×⌄`;};
const onRun=async()=>{const state=await post("/simulation/new-run");currentSpeed=state.speed;if(pause)pause.textContent="Ⅱ  Pause";if(speed)speed.textContent=`${currentSpeed}×⌄`;if(run){run.textContent="✓  New run";window.setTimeout(()=>{if(run)run.textContent="⟳  New run"},900);}};
const runAction=async(action:"blinds"|"fan")=>{const title=document.querySelector(".room-head h1")?.textContent??"Room";const id=title.toLowerCase().split("'")[0];try{const data=await post(`/rooms/${id}/action`,{action,value:action==="blinds"?"closed":"high"});if(data.error){setMessage(data.error);return;}setMessage(action==="blinds"?`✓ Blinds closed for ${title}`:`✓ Fan set to high for ${title}`);}catch{setMessage("Action could not be completed");}};
const onBlinds=(event:MouseEvent)=>{event.preventDefault();event.stopPropagation();void runAction("blinds");};const onFan=(event:MouseEvent)=>{event.preventDefault();event.stopPropagation();void runAction("fan");};
const createOffer=async(event:MouseEvent)=>{event.preventDefault();event.stopPropagation();const data=await post("/rooms/alice/offer-ac");setMessage(data.offer?"AC offer created. Approve it to start the session.":data.error??"Could not create AC offer");};
const bindActionFeedback=()=>Array.from(document.querySelectorAll<HTMLButtonElement>(".quick button")).forEach(button=>{if(button.dataset.feedbackBound)return;button.dataset.feedbackBound="true";button.addEventListener("click",button.textContent?.includes("Close blinds")?onBlinds:onFan);});
const bindInvoiceOffer=()=>Array.from(document.querySelectorAll<HTMLButtonElement>(".invoice-actions button")).forEach(button=>{if(button.textContent!=="Create AC offer"||button.dataset.offerBound)return;button.dataset.offerBound="true";button.addEventListener("click",createOffer);});
void fetch(`${api}/simulation`).then(response=>response.json()).then(state=>{currentSpeed=state.speed;if(pause)pause.textContent=state.paused?"▶  Resume":"Ⅱ  Pause";if(speed)speed.textContent=`${currentSpeed}×⌄`;}).catch(()=>{});
nav[0]?.addEventListener("click",onApartment);nav[1]?.addEventListener("click",onAnalytics);nav[2]?.addEventListener("click",onBilling);pause?.addEventListener("click",onPause);speed?.addEventListener("click",onSpeed);run?.addEventListener("click",onRun);bindActionFeedback();bindInvoiceOffer();const actionObserver=new MutationObserver(()=>{bindActionFeedback();bindInvoiceOffer();});actionObserver.observe(document.querySelector(".dash")!,{childList:true,subtree:true});
return()=>{nav[0]?.removeEventListener("click",onApartment);nav[1]?.removeEventListener("click",onAnalytics);nav[2]?.removeEventListener("click",onBilling);pause?.removeEventListener("click",onPause);speed?.removeEventListener("click",onSpeed);run?.removeEventListener("click",onRun);actionObserver.disconnect();};},[]);return message?<output aria-live="polite" style={{position:"fixed",right:20,bottom:20,zIndex:20,background:"#e1f6ea",color:"#146c43",padding:"10px 14px",borderRadius:8,fontWeight:700,boxShadow:"0 3px 12px #10233e44"}}>{message}</output>:null;}
