import pg from "pg";
import { newDb, DataType } from "pg-mem";
import crypto from "node:crypto";
import { isPaused, pricing, simulationSpeed } from "./simulation-control.js";
import { charge } from "./simulation.js";
export const usingDemoStorage=!process.env.DATABASE_URL;
const schema=`CREATE TABLE rooms (id TEXT PRIMARY KEY, tenant_name TEXT NOT NULL, temperature REAL NOT NULL, target_temp REAL NOT NULL, sunlight TEXT NOT NULL DEFAULT 'high', electronics TEXT NOT NULL DEFAULT 'on', blinds TEXT NOT NULL DEFAULT 'open', fan TEXT NOT NULL DEFAULT 'off', ac_on BOOLEAN NOT NULL DEFAULT false, ac_started_at TIMESTAMPTZ, ac_max_minutes INTEGER, ac_max_cents INTEGER, budget_cents INTEGER NOT NULL, free_actions TEXT[] NOT NULL DEFAULT '{}', revision INTEGER NOT NULL DEFAULT 1, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), pending_offer JSONB, active_session_id UUID, session_terms JSONB, ac_seconds INTEGER NOT NULL DEFAULT 0, last_accounted_at TIMESTAMPTZ NOT NULL DEFAULT now()); CREATE TABLE agent_steps (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), room_id TEXT, trigger TEXT NOT NULL, state_snapshot JSONB NOT NULL, reasoning TEXT, action TEXT, action_params JSONB, outcome TEXT, result_check TEXT, tool_result JSONB, evidence JSONB, check_status TEXT NOT NULL DEFAULT 'none', created_at TIMESTAMPTZ NOT NULL DEFAULT now()); CREATE TABLE invoices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), room_id TEXT, session_id UUID NOT NULL UNIQUE, ac_seconds INTEGER NOT NULL, rate_cents_per_hour INTEGER NOT NULL DEFAULT 120, amount_cents INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'draft', provider_id TEXT, payment_evidence JSONB, consent_summary JSONB, provider_request_id UUID, provider_progress TEXT, processed_event_ids JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL DEFAULT now()); INSERT INTO rooms (id,tenant_name,temperature,target_temp,budget_cents,free_actions,sunlight,electronics) VALUES ('alice','Alice',31.2,26,300,ARRAY['blinds','fan'],'high','on'),('bob','Bob',28.4,28,150,ARRAY['fan'],'low','off'),('chen','Chen',30,25.5,240,ARRAY['blinds','fan'],'medium','on'),('dana','Dana',29.5,26.5,60,ARRAY['blinds'],'high','on');`;
let memory:any; let memoryPg:any;
if(usingDemoStorage){memory=newDb();memory.public.registerFunction({name:"gen_random_uuid",returns:DataType.uuid,implementation:crypto.randomUUID});memory.public.none(schema);memoryPg=memory.adapters.createPg();}
export const pool:any=usingDemoStorage?new memoryPg.Pool():new pg.Pool({connectionString:process.env.DATABASE_URL});
const fanMeters=new Map<string,{seconds:number;rate:number}>();
export function startFanMeter(id:string){if(!fanMeters.has(id))fanMeters.set(id,{seconds:0,rate:pricing().fan_rate_cents_per_hour});}
export function fanAccrued(id:string){const meter=fanMeters.get(id);return meter?charge(meter.seconds,meter.rate):0;}
export async function room(id:string) { const r=await pool.query("SELECT * FROM rooms WHERE id=$1",[id]); return r.rows[0]; }
export async function settle(id:string) { const r=await room(id); if(!r||isPaused()) return r; const elapsed=Math.max(0,(Date.now()-new Date(r.last_accounted_at).getTime())/1000*simulationSpeed()); if(!elapsed)return r;if(r.fan!=="off"){startFanMeter(id);const meter=fanMeters.get(id)!;meter.seconds+=elapsed;}if(!r.ac_on){await pool.query("UPDATE rooms SET last_accounted_at=now() WHERE id=$1",[id]);return room(id);} const {advance}=await import("./simulation.js"); const rate=Number(r.session_terms?.rate_cents_per_hour??pricing().ac_rate_cents_per_hour); const next=advance({...r,ac_max_seconds:r.ac_max_minutes===null?null:r.ac_max_minutes*60,rate_cents_per_hour:rate},elapsed); await pool.query("UPDATE rooms SET temperature=$2, ac_seconds=$3, ac_on=$4, last_accounted_at=now(), updated_at=now(), revision=revision+1 WHERE id=$1",[id,next.temperature,Math.floor(next.ac_seconds),next.ac_on]); return room(id); }
export async function step(id:string, values:Record<string,unknown>) { const r=await pool.query("INSERT INTO agent_steps (id,room_id,trigger,state_snapshot,reasoning,action,action_params,outcome,result_check,tool_result,evidence,check_status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[crypto.randomUUID(),id,values.trigger,JSON.stringify(values.state),values.reasoning??null,values.action??null,JSON.stringify(values.params??{}),values.outcome??null,values.result??null,JSON.stringify(values.tool??{}),JSON.stringify(values.evidence??{}),values.check??"none"]);return r.rows[0]; }
export async function finish(id:string) { const r=await settle(id); if(!r?.active_session_id) return null; const rate=Number(r.session_terms?.rate_cents_per_hour??pricing().ac_rate_cents_per_hour); const amount=charge(r.ac_seconds,rate); const client=await pool.connect(); try{await client.query("BEGIN");const found=await client.query("SELECT * FROM invoices WHERE session_id=$1",[r.active_session_id]);if(found.rowCount){await client.query("COMMIT");return found.rows[0];}const added=await client.query("INSERT INTO invoices (room_id,session_id,ac_seconds,rate_cents_per_hour,amount_cents,consent_summary) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *",[id,r.active_session_id,r.ac_seconds,rate,amount,JSON.stringify(r.session_terms)]);await client.query("UPDATE rooms SET ac_on=false, active_session_id=null, budget_cents=budget_cents-$2, updated_at=now() WHERE id=$1",[id,amount]);await client.query("COMMIT");return added.rows[0];}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()} }
